name: xetzgpt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  provider: ^6.1.2
  google_fonts: ^6.2.0
  flutter_spinkit: ^5.2.1
  http: ^1.2.0
  animated_text_kit: ^4.2.2
  flutter_lints: ^4.0.0
  flutter_markdown: ^0.6.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
